### ISSUE TITLE
Run all of brian's examples as (manual) consistency

### ISSUE THREAD

**Issue by moritzaugustin** [brian-team/brian2cuda#114]
e.g. script looping and running the respective python file but within brian2cuda, plots to disk, output to disk

**Comment by denisalevi** [comment]
Currently most consistency tests are just producing figures for visual inspection (because they use some kind of randomness which does not allow straight forward result array comparison). But in many cases this is just e.g. some random intialisation, which could be done in python with a fixed seed, s.t. different code generation targets use the same initialisations.

**Comment by denisalevi** [comment]
Just saw that brian2 has a [run_examples.py](https://github.com/brian-team/brian2/blob/master/dev/tools/run_examples.py) that runs all python scripts in the examples folder. Adapting that to use standalone would be a quick solution for this issue. But it would mean only visual inspections fo the plots. But I guess thats fine for now.

**Comment by moritzaugustin** [comment]
visual inspection only was from the beginning what I though about w.r.t *this* (secondary) consistency check line (since it means little effort). of course if some examples do not run in standalone mode simply skip them, the rest are sufficiently many examples

**Comment by denisalevi** [comment]
I adapted brian2s run_examples.py (linked in my comment above) such that it runns all examples that it finds in the `brian2/examples` directory of the installed brian2 (using `brian2.__file__`) and saves the generated plots in the current directory.

About 2/3 of the examples failed due to 
1. multicompatment models (which are not working currently)
2. multiple run statements (which could probably be fixed with some more string substitution magic, but not worth it right now)
3. summed variable usage (which we haven't implemented yet)
4. some matplotlib bug I'm getting for `plt.plot(..., color='C0', ...)` syntax. documentation states `CN` kind of syntax, maybe I'm running an old matplotib (1.5 in my dev environment). Might be that.

Anyways, the 20/56 plots that were successfully created look like the ones I generated with `cython` runtime.

**Comment by denisalevi** [comment]
For reference, this is the script: [run_brian2_examples.py](https://github.com/brian-team/brian2cuda/blob/35d4d9ae64d30f2d504b1e40c1c3d39d45fc4db7/brian2cuda/tools/run_brian2_examples.py)

**Comment by mstimberg** [comment]
> some matplotlib bug I'm getting for plt.plot(..., color='C0', ...) syntax. documentation states CN kind of syntax, maybe I'm running an old matplotib (1.5 in my dev environment). Might be that.

Yes, this is a matplotlib 2.0 feature, we should maybe mention somewhere that the Brian examples expect matplotlib 2.x now...
