### ISSUE TITLE
IOError due to not written 'restuls/last_run_info.txt' in cuda_standalone mode

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#18]
When running a brian2 script in `cuda_standalone` mode with `compile=True` and `run=True` arguments for `device.build()`, following error is thrown:
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    device.build(directory='./', compile=True, run=True, debug=False)
  File "/mnt/antares_raid/home/denisalevi/projects/dev_brian2cuda/brian2cuda_repo/brian2cuda/device.py", line 586, in build
    self.run(directory, with_output, run_args)
  File "/home/denisalevi/anaconda2/envs/dev_b2c/lib/python2.7/site-packages/brian2/devices/cpp_standalone/device.py", line 797, in run
    last_run_info = open('results/last_run_info.txt', 'r').read()
IOError: [Errno 2] No such file or directory: 'results/last_run_info.txt'
```
This error can be reproduced with:
```
from brian2 import *
import brian2cuda                                                     

set_device('cuda_standalone')
device.build(directory='./', compile=True, run=True, debug=False)
```

@moritzaugustin could you check if you can reproduce this error?

The `CUDAStandaloneDevice` object calls the `CPPStandaloneDevice.run()` method (which it inherits) and that tries to open `results/last_run_info.txt`. In `cpp_standalone` mode, the created `objects.cpp` file writes the `results/last_run_info.txt` in its `_write_arrays()` function. In `cuda_standalone` mode, it doesn't. 

So either override the `run()` method in the `CUDAStandaloneDevice` class or change the `brian2cuda/templates/objects.cu` template to write the 'restuls/last_run_info.txt' file as done in `brian2/devices/cpp_standalone/templates/objects.cpp`.

Check functionality of `results/last_run_info.txt' file!

**Comment by moritzaugustin** [comment]
The problem might be caused by additional changes made by @Kwartke  in a series of small patches to the *frozen* brian2 commit `d82e7a4419e61d262126a96dc1bed35e37bac761` 
You can find these files here: https://github.com/moritzaugustin/brian2/tree/frozen

I think that @Kwartke told me that these changes were integrated into the main repository https://github.com/brian-team/brian2 but I am not sure about this.

@denisalevi Please check whether the patches are really required and if so please do a pull-request to (the current master branch of https://github.com/brian-team/brian2) such that in the final brian2 we can directly import the original brian2 not depending on any additional patches...

The latter would imply -- as far as I understand -- that the submodule track is not useful or that it should rather follow the frozen branch of moritzaugustin/brian2 than of original brian-team/brian2

**Comment by mstimberg** [comment]
Hi everyone,
AFAICT, all of @Kwartke's changes to Brian2 have been merged into master already. The merge was in November 2015 but your submodule still tracks the version from October.

**Comment by moritzaugustin** [comment]
@mstimberg Thanks for the information!

@denisalevi: Since between the commits of @Kwartke into brian-team/brian2 (those which are the most recent three ones in the frozen branch of moritzaugustin/brian2) and d82e7a4419e61d262126a96dc1bed35e37bac761 (commit that the submodule of brian2cuda was/is currently pointing to) there were a couple of other commits to brian-team/brian2. Before we know that also the commits of brian2genn and genn (see README) work with this more recent version we keep it for now as discussed with the frozen branch of moritzaugustin/brian2 and switch then later to the recent brian-team/brian2 when we have solved the open issues.

**Comment by denisalevi** [comment]
Yeah, I found the commits in brian2. Thanks @mstimberg.
@moritzaugustin I updated the submodule to track the frozen branch from `moritzaugustin/brian2`for now.
