### ISSUE TITLE
[how to] changing Synapses Weights after run with cpp/cuda

### ISSUE THREAD

**Issue by davideschiavone** [brian-team/brian2cuda#261]
I am running an application with Brian2 with Cuda

but every time I assign to my synapses weights a value from a matrix in a multiple run, Cuda/C++ fails.

offensive code: https://github.com/davideschiavone/SimpleMNIST/blob/main/mnist_example.py#L314

What I want to do is:

generating weights in numpy in a matrix (or maybe getting them from a file) and assign them to my Synapse.
After every run, I want to normalize them

https://github.com/davideschiavone/SimpleMNIST/blob/main/mnist_example.py#L415

I also assign a reward for supervising the training here: https://github.com/davideschiavone/SimpleMNIST/blob/main/mnist_example.py#L353

and I guess this will also fail.

I read that I should use the "string based assignments" from the Limitation section of the Documentation

https://brian2.readthedocs.io/en/2.0rc/user/computation.html#limitations

However, it is not clear to me how to do this. Is there any more detailed documentation for doing this?

**Comment by denisalevi** [comment]
Hi @davideschiavone,

you are asking for Brian2 support here, which is better directed to the [Brian Discourse Group](https://brian.discourse.group/).

I would advice you to first try to get your model working with the C++ Standalone backend (`set_device('cpp_standalone')`). Any questions that arise during that process are best directed to the Discourse Group, where there are just more people being able to help you.

Once Everything works with Brian2's C++ backend, you can move on to trying out a GPU backend (e.g. Brian2CUDA via `set_device('cuda_standalone')`, which should just work out of the box. If you have any issues in that transition step, a github issue here would be the right place to get support or a fix on that :tada:

But since you are already here, here are a few pointer on how to solve your problem:

1. Have a look at Brian's [Synapses](https://brian2.readthedocs.io/en/stable/user/synapses.html) documentation to see how string-based indexing works, specifically [this section](https://brian2.readthedocs.io/en/stable/user/synapses.html#accessing-synaptic-variables), which also gives you a pointer how to implement the normalization based on e.g. the number of pre- or postsynaptic neurons of any synapse.
2. In principle, in your loop you can replace the weight initialization:
    ```python
    for n0 in range(N0_Neurons):
        for n1 in range(N1_Neurons):
            S.w[n0,n1] = weight_matrix[n0, n1]
    ```
    with string-based syntax like this
    ```python
    for n0 in range(N0_Neurons):
        for n1 in range(N1_Neurons):
            S.w['i == n0 and j == n1'] = weight_matrix[n0, n1]
    ```
    The string-based index has to generate a boolean for each generated synapse (which you generate in the `S.connect(...)` call). In the string-based syntax, you can use Python variables defined in the current scope (like `n0` and `n1` here) and internal Brian2 variable (like `i` and `j`, which refer to the pre- and postsynaptic indices). To see the available internal variable, see [here](https://brian2.readthedocs.io/en/stable/user/synapses.html#model-syntax).
3. BUT each string-based assignment generates a separate code file that implements the assignment on C++ or CUDA site, so having many assignments each setting a single variable is inefficient. Instead, try to fit it into a single assignment. If you have an all-to-all connection for example, you could just use `S.w = weight_matrix.flat` (or maybe the matrix transpose, depending on how you connected the synapses).

For more details, I would have to read up on the documentation myself. I would suggest to post additional questions on the Discourse :)

**Comment by davideschiavone** [comment]
@denisalevi you are so kind - thanks a lot
I will be following your suggestions. By the way, once you have done with your deadlines (I have been through it many times too :)) we can have a chat about possible research collaborations. What do you think?

**Comment by denisalevi** [comment]
Sure, if there is an overlap in research interests, feel free to send me an email.
