### ISSUE TITLE
Why the volatile GPU utilization is so low? I run the same code respectively on the CPU(cpp_standalone) and GPU(brian2cuda), and i expect that it can run quickly by using brian2ccuda. However, it runs much slower... Can someone explain this? 

### ISSUE THREAD

**Issue by LiYuan-0709** [brian-team/brian2cuda#313]
![微信图片_20240301215921](https://github.com/brian-team/brian2cuda/assets/61772409/b05de1cd-adc1-4885-99fa-8b6e4b99e5a8)
**Runing on CPU set_device('cpp_standalone')**
![image](https://github.com/brian-team/brian2cuda/assets/61772409/5329af70-2bbe-47cf-8ae5-7b58b02146fe)

**Runing on GPU, set_device("cuda_standalone")**
![image](https://github.com/brian-team/brian2cuda/assets/61772409/06579380-9a0b-455f-a899-b742a4e3c7a4)

**Comment by mstimberg** [comment]
Hi @LiYuan-0709, could you please open a discussion thread on https://brian.discourse.group instead of this issue? This looks indeed very slow, but it might be simply be because of your model or the way your model is set up? Without any further details (about the model and your GPU)  we cannot really look into this. From the numbers on the CPU, it seems you are running a very small network for a very long time? This would be the worst-case scenario for a GPU, it needs many neurons/synapses to simulate in parallel. See our paper for more details: https://www.frontiersin.org/articles/10.3389/fninf.2022.883700/full
