### ISSUE TITLE
prevent excessive kernel register usage

### ISSUE THREAD

**Issue by moritzaugustin** [brian-team/brian2cuda#4]
it seems that big models (with many variables) lead to unexecutable kernels because of exceeding the max. no of registers per thread (https://en.wikipedia.org/wiki/CUDA). this is related with iss #5 

if this is indeed true we should change the storage of pointers within kernels from registers to shared or global memory

alternatively explicitly support only up to ... eqs and raise `NotImplemented` during code generation otherwise)

**Comment by denisalevi** [comment]
Currently device pointers - stored in host memory - are passed to our device kernels through `%KERNEL_VALUES%` and `%DEVICE_PARAMETERS%`. 

We could instead copy the device pointers to global gpu memory (using`CudaMemcpyToSymbol`) and use them directly without register usage. This will probably slow down the kernel though, since accessing the pointer would then be a global memory access. Maybe we could check for the number of needed registers and only copy pointers to global memory, when they would need too many registers. 

Or we start our kernels with copying the pointers to shared memory instead (taking care of coalesced memory accesses by having pointer addresses stored on concurrent global memory locations).
