### ISSUE TITLE
Adapt network activity to network size in benchmark models.

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#81]
Currently the network activity per neuron is independent of the network size in e.g. our CUBA or COBAHH benchmarks. Since both models have `O(num_neurons)` inputs per neuron, we should probably scale the weights down for higher network sizes to reduce the recurrent inputs.

**Comment by denisalevi** [comment]
And also add a Brunel Hakim with heterogeneous delays benchmark that operates in the same regime as our homogeneous delays benchmark (check paper for correct parameters). I wrote down that this should be for an external stimulus of mean 28 and sigma 0.5.

**Comment by moritzaugustin** [comment]
in addition or isntead of scaling the weights it would be interesting to see for linear number of synapses (e.g. fixed mean number of connections per neuron) vs quadratic one (e.g. connection probability leading to O(N) connections per neuron)

**Comment by moritzaugustin** [comment]
add models: CUBA and COBA as in the brian2/examples folder to speedtest (i.e., verisons without "fixed"connectivity)
=> manipulate them by scaling the coupling strengths (both E and I) in order to preserve average input to each cell (i.e., not the spiking activitiy is increased but the no of active synapses)
COBA: scale we and wi each with 4000/N_neurons
CUBA: scale we by 3200/(N_neurons*0.8), scale wi by 800/(N_neurons*0.2)

**Comment by thesamovar** [comment]
Careful with weight scaling. IIRC for large numbers of neurons in the CUBA example, with weight scaling it becomes fully synchronised (i.e. all neurons firing at exactly the same time). Fixing the number of synapses per neuron works much better.

**Comment by moritzaugustin** [comment]
good point, thanks. actually we would like to have both scenarios (one would have icnreased spike propagation over the other) but will keep an eye on whether we have a (weak coupling  induced) synchronization
